### ISSUE TITLE
sample.html reloads automatically to BASE_URL/#

### ISSUE THREAD

**Issue by halamix2** [razaibi/Wirup#1]
When I open `http://example.com/Wirup/sample.html` it automatically redirects to `http://example.com/#/`
Console returns `TypeError: _views[index] is undefined`at `Wirup.js:59:13`, tested in Firefox 66.0.3

**Comment by razpinator** [comment]
- @Halamix2  Firstly thank you bringing this to my attention. Yes, this is genuine bug and I have fixed it in my latest commits (on the Wirup.js and Wirup.min.js files) .

I have tested it in `Firefox 67.0b18` and `Chrome Version 76.0.3809.100`. I know this is a different version from the one you mentioned, but it should work all the same.

- With regard to navigating to sample.html, the framework has been designed to use **hash-based routing**. As a result, directing to specific pages like `http://yourpage.com/xyz.html`, may not and should not work.

Instead you are encouraged to define your different pages (**views** as I call them) in the **views.json** file found in the **views folder**.

Navigate to them based on the route (url) you have defined in the **views.json**  file.

For example, let us assume that you have defined a view this way **views.json**.
```
{
    "views": [
        {
            "viewName": "xyzView",
            "url": "/xyz",
            "HTML": "sample.txt"
        }
    ]
}
```

When you navigate to `http://yourpage.com/xyz`, you should be able to see your page now. 

Hope this helps. I am going to go ahead and close this issue. Feel free to raise a new one if you come across one.

Thanks!!
